config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'homes#top'
  get 'books/new'
  post 'books' => 'books#create'
  get 'books' => 'books#index', as: 'index_book'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: { message: "can't be blank" }
	validates :body, presence: { message: "can't be blank" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id), notice: 'Book was successfully created.'
    else
      @books = Book.all
      render action: :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'Book was successfully updated.'
    else
      render action: :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path, notice: 'Book was successfully destroyed.'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

  <% if @book.errors.any? %>
    <h3><%= @book.errors.count %> errors prohibited this book from being saved</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
  <label>Title</label>
  <%= f.text_field :title %>
  <lavel>Body</lavel>
  <%= f.text_area :body %>
  <%= f.submit 'Update Book' %>
  <%= link_to 'Show', book_path(@book.id) %>
  <%= link_to 'back', index_book_path%>
<% end %>

app/views/books/index.html.erb
    <p id="notice">
      <%= notice %>
    </p>

    <h1>Books</h1>
    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Body</th>
          <th colspan="3"></th>
        </tr>
      </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= book.title %></td>
              <td><%= book.body %></td>
              <td><%= link_to "Show", "/books/#{book.id}" %></td>
              <td><%= link_to "Edit", "/books/#{book.id}/edit" %></td>
              <td><%= link_to "Destroy", "/books/#{book.id}", method: :delete, "date-confirm" => "Are you sure?" %></td>
            </tr>
          <% end %>
        </tbody>
    </table>

    <h3>New book</h3>
    <%= form_for @book do |f| %>
      <% if @book.errors.any? %>
        <h3><%= @book.errors.count %> errors prohibited this book from being saved</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    <% end %>

    <%= form_with model: @book, url:'/books', local:true do |f| %>
      <h5>Title</h5>
      <%= f.text_field :title %>
      <h5>Body</h5>
      <%= f.text_area :body %>
      <%= f.submit 'Create Book' %>
    <% end %>

app/views/books/new.html.erb
<h3>New book</h3>
<%= form_with model: @book, url:'/books', local:true do |f| %>
  <h5>Title</h5>
  <%= f.text_field :title %>
  <h5>Body</h5>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>
  
  

app/views/books/show.html.erb
<p id="notice">
	<%= notice %> 
</p>

<th>Title:</th>
<p><%= @book.title %></p>
<th>Body:</th>
<p><%= @book.body %></p>
<%= link_to "edit", edit_book_path(@book.id) %>
<%= link_to "back", index_book_path %>

app/views/homes/top.html.erb
<h1>ようこそ <strong>Bookers</strong> へ！</h1>

<p>
	<strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や
</p>
<p>印象を共有し交換することができます。</p>

<%= link_to 'start', index_book_path(@book_id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>